name: ePlugin
api: 3.21.1
version: 1.0.0
author: LunarMoon72
mcpe-protocal: 448
main: LunarMoon72\ePlugin\Main
description: This is a test lol

command:
  e:
    description: This is e
    aliases: e
    permission: e.cmd

permissions:
  e.cmd:
    default: op
